### ISSUE TITLE
[Plugin] Spam Protection - View Spam Comment

### ISSUE THREAD

**Issue by Tangol** [MercanoG/Osclass-Enterprise#1]
When viewing a spam comment posted by an unregistered user, the **author name** is empty.
It's returning `$user['s_name']` which is available only for logged-in users.

The field should return the author name, even if the user is not registered, like in the Comments section (should probably return `s_author_name`).

**Comment by MercanoGlobal** [comment]
Fixed by https://github.com/MercanoG/Osclass-Enterprise/commit/e8d566149c6b8ef024b6b472030547b2eaad2f2b
