### ISSUE TITLE
[Plugin] Spam Protection - Blocked Mail Hoster at Comment/Contact

### ISSUE THREAD

**Issue by Tangol** [MercanoG/Osclass-Enterprise#4]
The **Blocked Mail Hoster** for both **Comments** and **Contacts**, doesn't work.

These 2 use the same code logic, so fixing one means fixing the other.

**Comment by MercanoGlobal** [comment]
Fixed by https://github.com/MercanoG/Osclass-Enterprise/commit/eacf964640b9bd6d01942c5cd44a40cc7ba9ae65
