### ISSUE TITLE
Can't Send Email Verification

### ISSUE THREAD

**Issue by mhakim168** [MercanoG/Osclass-Enterprise#7]
I have this error on admin panel caused the email verification wont send the email :
![image](https://user-images.githubusercontent.com/35446586/179432536-e0634ea2-e759-4009-8a88-e0b5641a5e14.png)

is there someone can help me fix this?

**Comment by Tangol** [comment]
@mhakim168 Please note that your hosting is missing **SSL** (Apache mod_ssl), and without it the SMTP authentication is not functional.
Also, some hosts don't allow SMTP authentication, so be sure to try with & without this setting.

PS: POP must be unchecked.
