### ISSUE TITLE
Searching on a multilingual site does not work

### ISSUE THREAD

**Issue by bsico** [MercanoG/Osclass-Enterprise#8]
Search results do not appear in all languagesFor example, if a person searches for BMW, the results will not appear for him unless he chooses the English language, but if he chooses another language, the results will not appear as if there is no item with that title.

Most sites of this type must include multiple languages, such as:French - English - Spanish - ItalianAll the languages I mentioned have the same names for cars, for exampleBMW is written with the same form, meaning and letters in all

**Comment by MercanoGlobal** [comment]
Sorry, but we can't confirm this issue.

- We created 2 listings, titled: **BMW X6 M** and **New Mercedes Benz**.
- We tried searching with the following languages active: Chinese, Norwegian and Spanish.
- All search combinations worked correctly in all languages. Example searches: `bmw`, `mercede`, `mercedes benz`.

Please provide more information about your environment, like: Server and PHP Version, Osclass Version, Theme Name and Version, Languages Used.

**Comment by MercanoGlobal** [comment]
Since no other feedback was offered, we consider this report as invalid.
